- name: Install Runtime and Kubernetes
  hosts:
    - masters
    - workers
  roles:
    - update-pkgs
    - runtime
    - download-k8s
    - install-k8s

- name: Install networking - calico
  hosts: masters
  roles:
    - role: install-calico
      when: cni_provider == "calico"

- name: Install networking - flannel
  hosts:
    - masters
    - workers
  roles:
    - role: install-flannel
      when: cni_provider == "flannel"
