- name: Install Runtime and Kubernetes
  hosts:
    - masters
    - workers
  vars:
    directory: release
  roles:
    - runtime
    - download-k8s
    - install-k8s

- name: Install networking - calico
  hosts: masters
  roles:
    - install-calico

- name: Install nfs server & client
  hosts: masters
  roles:
    - install-nfs
