- name: Cordon master node
  shell:
     "kubectl get node --selector='node-role.kubernetes.io/control-plane' --no-headers | awk '{print $1}' | xargs kubectl cordon"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# The /metrics API access needs to be enabled to scrape the scheduler metrics.
# The role associated by the scraper is system:anonymous, hence a Cluster role and a binding is added to enable the API access.
- name: Add RBAC for /metrics API access
  shell: |
     kubectl create clusterrole metrics-viewer --verb=get --non-resource-url=/metrics
     kubectl create clusterrolebinding perf-metrics-user --clusterrole metrics-viewer --user system:anonymous

# Hold-off from executing tests until all nodes in cluster are Ready
- name: Wait for nodes to transistion to Ready state
  shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
