- name: Install prereq packages
  package:
    name:
      - git
      - make
      - gcc
    state: present
  when: ansible_pkg_mgr in ['yum','dnf']

- name: Update apt-get repo/cache and install prereq packages
  apt:
    force_apt_get: yes
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - make
      - gcc
      - jq
  when: ansible_pkg_mgr == 'apt'

- name: Create a shell script
  copy:
    content: |
      #!/bin/bash
      set -o errexit

      echo 'This is a script to run k8s UT tests'

      useradd -s /bin/bash -d /home/nonroot -m nonroot

      su - nonroot <<EOF
      set -o errexit

      git clone https://github.com/kubernetes/kubernetes
      pushd kubernetes
      export CGO_ENABLED=1
      export KUBE_TIMEOUT='--timeout=600s'
      export KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
      export LOG_LEVEL=4
      export ARTIFACTS=~/artifacts
      git checkout {{ k8s_branch }}
      make test KUBE_RACE=-race
      popd
      EOF
    dest: /make-test.sh
    mode: '0755'
