- name: Add Redhat Subscription
  block:
    - name: check username and password are set
      fail:
        msg: "username and password are the mandatory values to execute the playbook for rhel"
      when:  ansible_distribution == "RedHat" and  username is not defined or password is not defined

    - name: Register RHEL
      shell: subscription-manager register --username {{ username }} --password {{ password }} --auto-attach
      when:  ansible_distribution == "RedHat"

- name: Update packages and kernel to latest available versions
  package:
    name: '*'
    state: latest
  when: ansible_pkg_mgr in ['yum', 'dnf']

- name: Check if reboot required
  shell: needs-restarting -r
  register: reboot_check
  ignore_errors: yes
  when: ansible_distribution in ['CentOS', 'RHEL']

- name: Reboot if necessary
  reboot:
  when: reboot_check.rc == 1 and ansible_distribution in ['CentOS', 'RHEL']

