- name: Generate download URL based on S3 server.
  set_fact:
    src_template: >-
      {% if s3_server == 'dl.k8s.io' -%}
        https://{{ s3_server }}/{{ directory }}/{{ build_version }}
      {%- else -%}
        https://{{ s3_server }}/{{ bucket }}/{{ directory }}/{{ build_version }}
      {%- endif %}

- name: Extract the k8s bits
  unarchive:
    src: "{{ src_template }}/{{ item }}"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts:
      - --strip-components=3
  with_items:
    - kubernetes-test-linux-ppc64le.tar.gz
    - kubernetes-client-linux-ppc64le.tar.gz
    - kubernetes-server-linux-ppc64le.tar.gz
  retries: 3
  delay: 5
